### ISSUE TITLE
How to install in chromium-based Vivaldi browser

### ISSUE THREAD

**Issue by Dricc123** [kiwix/kiwix-js-pwa#625]
in Vivaldi browser, the pwa.kiwix.org configuration page tells me that "Version 3.3.8 is ready to load (re-launch app to load)". And there is no 'Install' button on the page.
I haven't tried in other browsers

**Comment by Jaifroid** [comment]
@Dricc123 I haven't used Vivaldi on Android. Did you try pressing the "Reset" button, as this will usually clear the Service Worker and load the latest. I'll try myself and get back to you.

**Comment by Jaifroid** [comment]
OK @Dricc123 there are two issues here:

1. Updating to v3.3.8: assuming you did relaunch the app (close the tab and re-open, or better, exit Vivaldi and re-open), and if "Version 3.3.8 is ready to load still shows", then try pressing the "Reset" button (in app: a small one near top of Configuration, also a larger button under Troubleshooting and Development).
2. Installing the PWA as a standalone app: The only reason I'm aware that the "Install" button won't appear is probably because the app thinks there is already an installation of the PWA in Chrome. Take a look at the "V" menu in Vivaldi and see if it has the "Open Kiwix PWA" as in screenshot below. If it doesn't, does it have an option like "Add to home screen" or "Install"?

![image](https://github.com/user-attachments/assets/67d83c04-aea7-4a0d-b587-13f9bbd75f6d)

I'm having difficulty reproducing your issues because I already have the PWA installed, so Vivaldi just shows me this menu, which opens the Chrome PWA.

**Comment by Dricc123** [comment]
Oh, PWA are for mobile only!
Yes, why would we need PWA on Desktop in the first place... I should have thought about this before posting my question
Thank you so much for trying to help.

**Comment by Dricc123** [comment]
Then my question is valid :-)
I'm not sure why I don't get the Install button. I checked on Edge browser and the button is there

**Comment by Jaifroid** [comment]
So, I've tried on Vivaldi desktop, and it seems that that browser does not provide the `onBeforeInstallEvent()` that other Chromium browsers have. But you can still install the app by right-clicking the tab at the top of the browser (the tab of the PWA's page) and choosing the circled item in screenshot below. I just tried it, and it works fine even thought I have the PWA installed from Chrome. It just creates a second copy of the PWA running in the Vivaldi engine instead.

![image](https://github.com/user-attachments/assets/5ce67fab-016c-42fc-b79f-d3fbc4e69661)

**Comment by Jaifroid** [comment]
> Then my question is valid :-) I'm not sure why I don't get the Install button. I checked on Edge browser and the button is there

@Dricc123  See previous reply showing how to install it, but the reason is that Vivaldi devs have either chosen not to provide the UI for the in-app install procedure, or are suppressing it for security reasons. But they provide their own way to install as a system app, which works fine as mentioned.

**Comment by Dricc123** [comment]
Perfect! It's perfectly fine for me that Vivaldi works this way. Just needed to know how to. Thanks a lot for looking it up and solving my concern! Best regards,

**Comment by Jaifroid** [comment]
Glad to have been able to help resolve the issue!
